media_folder: static/images
public_folder: /images
backend:
  name: git-gateway
  branch: master
collections:
  - name: post
    label: Posts
    folder: content/posts
    create: true
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: >-
          The title of the blog post
      - widget: date
        name: date
        label: Date
        required: true
        hint: >-
          The date the post is published
      - widget: string
        name: slug
        label: Slug
        required: true
        hint: >-
          The post URL (do not include folder or file extension)
      - widget: relation
        name: author
        label: Author
        required: true
        hint: >-
          The author of the post
        collection: author
        valueField: slug
        searchFields: ["title"]
        displayFields: ["title"]
      - widget: relation
        name: related_posts
        label: Related Posts
        required: false
        multiple: true
        hint: >-
          Other related posts
        collection: post
        valueField: slug
        searchFields: ["title"]
        displayFields: ["title"]
      - widget: markdown
        name: body
        label: Content
        required: true
        hint: Page content
  - name: author
    label: Authors
    folder: content/authors
    create: true
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Name
        required: true
        hint: >-
          The name of the author
      - widget: string
        name: slug
        label: Slug
        required: true
        hint: >-
          The post URL (do not include folder or file extension)
      - widget: markdown
        name: body
        label: Content
        required: true
        hint: Author bio